export const NotificationType = {
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',

  WORK_ASSIGNED: 'WORK_ASSIGNED',
  WORK_REASSIGNED: 'WORK_REASSIGNED',
  WORK_UPDATED: 'WORK_UPDATED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  WORK_SENT_BACK: 'WORK_SENT_BACK',
  WORK_CARRIED_FORWARD: 'WORK_CARRIED_FORWARD',
  WORK_EMERGENCY: 'WORK_EMERGENCY',

  COMMENT_ADDED: 'COMMENT_ADDED',
  CONCERN_REPORTED: 'CONCERN_REPORTED',
  CONCERN_RESOLVED: 'CONCERN_RESOLVED',

  PROJECT_UPDATED: 'PROJECT_UPDATED',
  MILESTONE_UPDATED: 'MILESTONE_UPDATED',
  TARGET_UPDATED: 'TARGET_UPDATED',

  MENTION: 'MENTION',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
} as const

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType]
