export const NotificationType = {
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',

  WORK_ASSIGNED: 'WORK_ASSIGNED',
  WORK_REASSIGNED: 'WORK_REASSIGNED',
  WORK_UPDATED: 'WORK_UPDATED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  WORK_SENT_BACK: 'WORK_SENT_BACK',
  WORK_CARRIED_FORWARD: 'WORK_CARRIED_FORWARD',
  WORK_EMERGENCY: 'WORK_EMERGENCY',
  WORK_BLOCKED: 'WORK_BLOCKED',

  DEADLINE_REMINDER: 'DEADLINE_REMINDER',
<<<<<<< HEAD
=======
  DEADLINE_APPROACHING: 'DEADLINE_APPROACHING',
>>>>>>> 4047dda (Deploy V2 with work tracking, targets, deadlines and manager access)
  DEADLINE_WARNING: 'DEADLINE_WARNING',
  DEADLINE_CRITICAL: 'DEADLINE_CRITICAL',
  DEADLINE_URGENT: 'DEADLINE_URGENT',
  WORK_OVERDUE: 'WORK_OVERDUE',
  WORK_ESCALATED: 'WORK_ESCALATED',
  PACING_BEHIND: 'PACING_BEHIND',
<<<<<<< HEAD
=======

  DAILY_REPORT_REMINDER: 'DAILY_REPORT_REMINDER',
  DAILY_REPORT_SUBMITTED: 'DAILY_REPORT_SUBMITTED',
>>>>>>> 4047dda (Deploy V2 with work tracking, targets, deadlines and manager access)

  COMMENT_ADDED: 'COMMENT_ADDED',
  CONCERN_REPORTED: 'CONCERN_REPORTED',
  CONCERN_RESOLVED: 'CONCERN_RESOLVED',

  PROJECT_UPDATED: 'PROJECT_UPDATED',
  MILESTONE_UPDATED: 'MILESTONE_UPDATED',
  TARGET_UPDATED: 'TARGET_UPDATED',

  MENTION: 'MENTION',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
} as const

export type NotificationTypeValue =
  (typeof NotificationType)[keyof typeof NotificationType]
